### ISSUE TITLE
id is invalid error on mesh-graph

### ISSUE THREAD

**Issue by mhkarimi1383** [kumahq/kuma-grafana-datasource#296]
### What happened?

```json
{"message":"id is invalid","traceID":""}
```

**Comment by mhkarimi1383** [comment]
Fixed by putting Prometheus info into plugin setting

But I'm using VictoriaMetrics Plugin for my main data source

Would be great if we could have support for that too

**Comment by slonka** [comment]
> triage: can you share more details about the fix? also can you share more info about how you set up VictoriMetrics? The best thing would be: 1. What you got. 2. What you expected to see. 3. Steps to reproduce.

**Comment by mhkarimi1383** [comment]
@slonka Fixed by providing Prometheus configs to datasource

**Comment by lukidzi** [comment]
@mhkarimi1383 Thanks
